version: "3.8"

services:

  baget:
    image: loicsharma/baget:latest
    container_name: baget
    ports:
        - "8000:8000"
    environment:
      - BAGET_DATABASE_CONNECTIONSTRING=Data Source=/data/baget.db
      - BAGET_STORAGE_TYPE=FileSystem
      - BAGET_STORAGE_PATH=/data/packages
      - BAGET_API_KEY=3-1375-1-1375-3-1375
    volumes:
      - ./data:/data
    networks:
      - domic

  nginx.nuget:
    build:
      context: .
      dockerfile: Dockerfile.Nginx
    container_name: nginx_nuget
    networks:
      - domic
    ports:
      - "443:443"
      - "80:80"

networks:
  domic:
    external: true