version: "3.8"

services:
  domic.registry:
    image: registry:2
    container_name: registry
    restart: always
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
    ports:
      - "6200:443"