version: "3.8"

services:

  dotris.nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotris_nginx
    networks:
      - domic
    ports:
      - "443:443"
      - "80:80"

networks:
  domic:
    external: true